trigger:
- main

pool:
  name: 'Default'  # Self-hosted pool kullanacak

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore and Build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration Release'
