CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "OutboxMessage" (
    "Id" uuid NOT NULL,
    "EventType" character varying(256) NOT NULL,
    "Payload" text NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    "RetryCount" integer NOT NULL,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" uuid NOT NULL,
    "CreatorId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "StartedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" character varying(512) NOT NULL,
    "TokenHash" character varying(128),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByIp" character varying(64),
    "RevokedAt" timestamp with time zone,
    "RevokedByIp" character varying(64),
    "ReplacedByToken" character varying(512),
    "RevokeReason" character varying(128),
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Modules" (
    "Id" uuid NOT NULL,
    "ProjectId" uuid NOT NULL,
    "CreatorId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "StartedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Modules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Modules_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UseCases" (
    "Id" uuid NOT NULL,
    "ModuleId" uuid NOT NULL,
    "CreatorId" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "ImportantNotes" character varying(500),
    "StartedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_UseCases" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UseCases_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Tasks" (
    "Id" uuid NOT NULL,
    "UseCaseId" uuid NOT NULL,
    "CreatorId" uuid NOT NULL,
    "AssigneeId" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000),
    "ImportantNotes" character varying(1000),
    "StartedDate" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone,
    "TaskType" integer NOT NULL,
    "TaskState" integer NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tasks_UseCases_UseCaseId" FOREIGN KEY ("UseCaseId") REFERENCES "UseCases" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TaskRelations" (
    "Id" uuid NOT NULL,
    "SourceTaskId" uuid NOT NULL,
    "TargetTaskId" uuid NOT NULL,
    "RelationType" integer NOT NULL,
    "TaskId" uuid,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_TaskRelations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskRelations_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("Id")
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Modules_ProjectId" ON "Modules" ("ProjectId");

CREATE INDEX "IX_OutboxMessage_OccurredAt" ON "OutboxMessage" ("OccurredAt");

CREATE INDEX "IX_OutboxMessage_ProcessedAt" ON "OutboxMessage" ("ProcessedAt");

CREATE INDEX "IX_Projects_StartedDate" ON "Projects" ("StartedDate");

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");

CREATE INDEX "IX_RefreshTokens_UserId_RevokedAt" ON "RefreshTokens" ("UserId", "RevokedAt");

CREATE INDEX "IX_TaskRelations_TaskId" ON "TaskRelations" ("TaskId");

CREATE INDEX "IX_Tasks_AssigneeId" ON "Tasks" ("AssigneeId");

CREATE INDEX "IX_Tasks_UseCaseId" ON "Tasks" ("UseCaseId");

CREATE INDEX "IX_UseCases_ModuleId" ON "UseCases" ("ModuleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251009204626_InitialCreate', '9.0.0');

COMMIT;

